name: Run 100 Proxyrack POP Containers

on:
  workflow_dispatch:

jobs:
  run-pop:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Run 100 containers with unique proxies
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          # Read proxies into an array
          wget https://raw.githubusercontent.com/kanekikun07/Yo/refs/heads/main/proxy.py
          pip install requests
          python proxy.py
          mapfile -t proxies < proxies.txt
          total=${#proxies[@]}

          if [ $total -lt 100 ]; then
            echo "Error: Not enough proxies in proxies.txt (found $total, need 100)"
            exit 1
          fi

          # Shuffle proxies to randomize assignment
          shuffled=($(shuf -e "${proxies[@]}"))

          for i in $(seq 1 100); do
            UUID="86c5f5d55f2317e7e852b1ae02b2e3b5388e18a51f848931508bc892935c8719"
            DEVICE_NAME="device_$i"
            PROXY=${shuffled[$((i-1))]}

            echo "Starting container $i with proxy $PROXY"

            docker run -d \
              -e UUID=$UUID \
              -e API_KEY=$API_KEY \
              -e DEVICE_NAME=$DEVICE_NAME \
              -e PROXY=$PROXY \
              proxyrack/pop:latest
          done
