name: Run 100 Containers with Proxychains and Unique Proxies

on:
  workflow_dispatch:

jobs:
  run-proxychains:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker image with proxychains
        run: |
          docker build -t proxychains-image .

      - name: Run 100 containers with unique proxies
        run: |
          chmod +x dock.sh
          ./dock.sh
